package atmProyekPBO.view;

import atmProyekPBO.ATMController;
import atmProyekPBO.User;
import java.awt.Color;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

import java.util.List;

import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;





public class DashboardView extends javax.swing.JPanel {

    private ATMView parentView = null;
     private static final Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
     private static User loggedInUser;
     private static DecimalFormatSymbols rupiahFormatSymbols = new DecimalFormatSymbols();
     private static DecimalFormat rupiahFormat = (DecimalFormat)DecimalFormat.getCurrencyInstance();
    
    /**
     * Creates new form MainPanel
 
     */
    public DashboardView() {
        initComponents();
        trfAmountTF.addKeyListener(new OnlyNumberKeyAdapter());
        trfAmountTF.addKeyListener(new LengthLimitKeyAdapter());
        
        withDrawAmountTF.addKeyListener(new OnlyNumberKeyAdapter());
        withDrawAmountTF.addKeyListener(new LengthLimitKeyAdapter());
        
        

        balanceTF.setEditable(false);
        rupiahFormatSymbols.setCurrencySymbol("Rp. ");
        rupiahFormatSymbols.setMonetaryDecimalSeparator(',');
        rupiahFormatSymbols.setGroupingSeparator('.');
        rupiahFormat.setDecimalFormatSymbols(rupiahFormatSymbols);
    
    }
    
    public void setParentView(ATMView parentview){
        this.parentView = parentview;
        
    }
    
    public void setLoggedInUser(User u){
        loggedInUser = u;
        this.balanceTF.setText(rupiahFormat.format(loggedInUser.getBalance()));
        this.accountNumberTF.setText(loggedInUser.getAccountNo());
        this.fullnameTF.setText(loggedInUser.getFullName());
        
    }
    
    
    private class LengthLimitKeyAdapter extends KeyAdapter{
        @Override
        public void keyTyped(KeyEvent e) {
            JTextField input  = (JTextField) e.getSource();
            if(input.getText().length()==1 && input.getText().equals("0")){
                input.setText("");
            }
            if(input.getText().length()>9){
                getToolkit().beep();
                e.consume();
            }
            
        }
    }
    
    private class OnlyNumberKeyAdapter extends KeyAdapter{
        @Override
        public void keyTyped(KeyEvent e) {
            
            char c = e.getKeyChar();
            if (!((c >= '0') && (c <= '9') ||
               (c == KeyEvent.VK_BACK_SPACE) ||
               (c == KeyEvent.VK_DELETE))) {
              getToolkit().beep();
              e.consume();
            }
        }
       
    }
    
    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        withdrawDialog = new javax.swing.JDialog();
        withDrawAmountTF = new javax.swing.JTextField();
        withdrawalConfirmBtn = new javax.swing.JButton();
        withdrawalCancelBtn = new javax.swing.JButton();
        transferDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        trfAmountTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        trfConfirmBtn = new javax.swing.JButton();
        trfCancelBtn = new javax.swing.JButton();
        depositDialog = new javax.swing.JDialog();
        depositAmountTF = new javax.swing.JTextField();
        depositConfirmBtn = new javax.swing.JButton();
        depositCancelBtn = new javax.swing.JButton();
        labelSelamatDatang = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        welcomeSeparator = new javax.swing.JSeparator();
        accountNumberTF = new javax.swing.JLabel();
        fullnameTF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelTransfer = new javax.swing.JPanel();
        transferBtn = new javax.swing.JButton();
        panelWithdrawal = new javax.swing.JPanel();
        withdrawalBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        depositBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        withdrawDialog.setTitle("JUMLAH TARIKAN");
        withdrawDialog.setAutoRequestFocus(false);
        withdrawDialog.setBackground(new java.awt.Color(255, 255, 255));
        withdrawDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        withdrawDialog.setMinimumSize(new java.awt.Dimension(200, 200));
        withdrawDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        withDrawAmountTF.setBackground(new java.awt.Color(51, 153, 255));
        withDrawAmountTF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        withDrawAmountTF.setForeground(new java.awt.Color(255, 255, 255));
        withDrawAmountTF.setText("0");

        withdrawalConfirmBtn.setBackground(new java.awt.Color(0, 102, 255));
        withdrawalConfirmBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        withdrawalConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalConfirmBtn.setText("TARIK");
        withdrawalConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalConfirmBtnActionPerformed(evt);
            }
        });

        withdrawalCancelBtn.setBackground(new java.awt.Color(204, 0, 0));
        withdrawalCancelBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        withdrawalCancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalCancelBtn.setText("BATAL");
        withdrawalCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawDialogLayout = new javax.swing.GroupLayout(withdrawDialog.getContentPane());
        withdrawDialog.getContentPane().setLayout(withdrawDialogLayout);
        withdrawDialogLayout.setHorizontalGroup(
            withdrawDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(withdrawDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(withdrawDialogLayout.createSequentialGroup()
                        .addComponent(withdrawalConfirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(withdrawalCancelBtn))
                    .addComponent(withDrawAmountTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        withdrawDialogLayout.setVerticalGroup(
            withdrawDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(withDrawAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(withdrawDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawalCancelBtn)
                    .addComponent(withdrawalConfirmBtn))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        transferDialog.setTitle("Transfer Saldo");
        transferDialog.setBackground(new java.awt.Color(153, 255, 255));
        transferDialog.setModal(true);

        userTable.setBackground(new java.awt.Color(51, 204, 255));
        userTable.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        userTable.setForeground(new java.awt.Color(0, 153, 204));
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Rek", "Atas Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setGridColor(new java.awt.Color(255, 255, 255));
        userTable.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(userTable);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tujuan Transfer (pilih satu)");

        trfAmountTF.setBackground(new java.awt.Color(51, 153, 255));
        trfAmountTF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        trfAmountTF.setForeground(new java.awt.Color(255, 255, 255));
        trfAmountTF.setText("0");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Trf");

        trfConfirmBtn.setBackground(new java.awt.Color(0, 102, 255));
        trfConfirmBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        trfConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        trfConfirmBtn.setText("TRANSFER");
        trfConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trfConfirmBtnActionPerformed(evt);
            }
        });

        trfCancelBtn.setBackground(new java.awt.Color(204, 0, 0));
        trfCancelBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        trfCancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        trfCancelBtn.setText("CANCEL");
        trfCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trfCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferDialogLayout = new javax.swing.GroupLayout(transferDialog.getContentPane());
        transferDialog.getContentPane().setLayout(transferDialogLayout);
        transferDialogLayout.setHorizontalGroup(
            transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transferDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(81, 81, 81))
                    .addGroup(transferDialogLayout.createSequentialGroup()
                        .addComponent(trfAmountTF, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trfConfirmBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trfCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        transferDialogLayout.setVerticalGroup(
            transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferDialogLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trfAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(transferDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trfConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trfCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        depositDialog.setTitle("JUMLAH TARIKAN");
        depositDialog.setAutoRequestFocus(false);
        depositDialog.setBackground(new java.awt.Color(255, 255, 255));
        depositDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        depositDialog.setMinimumSize(new java.awt.Dimension(200, 200));
        depositDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        depositAmountTF.setBackground(new java.awt.Color(51, 153, 255));
        depositAmountTF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        depositAmountTF.setForeground(new java.awt.Color(255, 255, 255));
        depositAmountTF.setText("0");

        depositConfirmBtn.setBackground(new java.awt.Color(0, 102, 255));
        depositConfirmBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        depositConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositConfirmBtn.setText("DEPO");
        depositConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositConfirmBtnActionPerformed(evt);
            }
        });

        depositCancelBtn.setBackground(new java.awt.Color(204, 0, 0));
        depositCancelBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        depositCancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositCancelBtn.setText("BATAL");
        depositCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositDialogLayout = new javax.swing.GroupLayout(depositDialog.getContentPane());
        depositDialog.getContentPane().setLayout(depositDialogLayout);
        depositDialogLayout.setHorizontalGroup(
            depositDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(depositDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(depositDialogLayout.createSequentialGroup()
                        .addComponent(depositConfirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depositCancelBtn))
                    .addComponent(depositAmountTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        depositDialogLayout.setVerticalGroup(
            depositDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(depositAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(depositDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositCancelBtn)
                    .addComponent(depositConfirmBtn))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(0, 153, 255));

        labelSelamatDatang.setBackground(new java.awt.Color(51, 51, 51));
        labelSelamatDatang.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        labelSelamatDatang.setText("SELAMAT DATANG DI ATM PROYEK PBO");

        logoutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        welcomeSeparator.setBackground(new java.awt.Color(255, 255, 255));

        accountNumberTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        accountNumberTF.setForeground(new java.awt.Color(255, 255, 255));
        accountNumberTF.setText("DEL12313");

        fullnameTF.setForeground(new java.awt.Color(255, 255, 255));
        fullnameTF.setText("FULLNAME");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sisa Saldo ");

        balanceTF.setBackground(new java.awt.Color(51, 204, 255));
        balanceTF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        balanceTF.setForeground(new java.awt.Color(255, 255, 255));
        balanceTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nama Pemilik");

        jTabbedPane1.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 204));
        jTabbedPane1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        panelTransfer.setBackground(new java.awt.Color(102, 204, 255));

        transferBtn.setBackground(new java.awt.Color(0, 102, 255));
        transferBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        transferBtn.setForeground(new java.awt.Color(255, 255, 255));
        transferBtn.setText("TRANSFER");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(transferBtn)
                .addContainerGap(573, Short.MAX_VALUE))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(transferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRANSFER", panelTransfer);

        panelWithdrawal.setBackground(new java.awt.Color(102, 204, 255));

        withdrawalBtn.setBackground(new java.awt.Color(0, 102, 255));
        withdrawalBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        withdrawalBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalBtn.setText("TARIK TUNAI");
        withdrawalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWithdrawalLayout = new javax.swing.GroupLayout(panelWithdrawal);
        panelWithdrawal.setLayout(panelWithdrawalLayout);
        panelWithdrawalLayout.setHorizontalGroup(
            panelWithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithdrawalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawalBtn)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        panelWithdrawalLayout.setVerticalGroup(
            panelWithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithdrawalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(withdrawalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PENARIKAN", panelWithdrawal);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        depositBtn.setBackground(new java.awt.Color(0, 102, 255));
        depositBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        depositBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositBtn.setText("DEPOSIT");
        depositBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                depositBtnComponentHidden(evt);
            }
        });
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(depositBtn)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DEPOSIT", jPanel1);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("No Rek ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelSelamatDatang)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(accountNumberTF)
                            .addGap(18, 18, 18)
                            .addComponent(logoutBtn))
                        .addComponent(welcomeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fullnameTF)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelamatDatang)
                    .addComponent(logoutBtn)
                    .addComponent(accountNumberTF)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnameTF)
                    .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        ATMController.getInstance().onUserLogout();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void withdrawalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalBtnActionPerformed
        withdrawDialog.getContentPane().setBackground( new Color(0,153,255) );
        withdrawDialog.setSize(200, 200);
        withdrawDialog.pack();
        withdrawDialog.setLocation((dim.width - withdrawDialog.getWidth()) / 2, (dim.height - withdrawDialog.getHeight()) / 2);
        withdrawDialog.setResizable(false);
        withdrawDialog.setVisible(true);
       
    }//GEN-LAST:event_withdrawalBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        List<Map<String,String>> users = User.getUsers();
        DefaultTableModel m = (DefaultTableModel) userTable.getModel();
        userTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        m.setRowCount(0);    
        for(final Map<String,String> item : users) {
            if(!item.get("accountNo").equals(ATMController.getInstance().getModel().getAccountNo())){
                 m.addRow(new String[]{item.get("accountNo"),item.get("fullname")});
            }  
        }
        transferDialog.getContentPane().setBackground(new Color(0,153,255) );
        transferDialog.setSize(300, 500);
        transferDialog.pack();
        transferDialog.setLocation((dim.width - transferDialog.getWidth()) / 2, (dim.height - transferDialog.getHeight()) / 2);
        transferDialog.setResizable(false);
        
        transferDialog.setVisible(true);
       
        
    }//GEN-LAST:event_transferBtnActionPerformed

    private void withdrawalConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalConfirmBtnActionPerformed
       Integer amount = Integer.parseInt(withDrawAmountTF.getText());
       boolean success = ATMController.getInstance().doWithdrawal(amount);
       if(amount==0){
           JOptionPane.showMessageDialog(null, "Silahkan masukkkan jumlah tarik tunai yang valid (min Rp 1)","AMOUNT INVALID",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       if(success){
           JOptionPane.showMessageDialog(null, "Tarik Tunai Berhasil","STATUS TARIK TUNAI",JOptionPane.INFORMATION_MESSAGE);
       }else{
            JOptionPane.showMessageDialog(null, "Tarik Tunai Gagal\nPastikan saldo anda masih mencukupi","STATUS TARIK TUNAI",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_withdrawalConfirmBtnActionPerformed

    private void trfConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trfConfirmBtnActionPerformed
        Integer amount = Integer.parseInt(trfAmountTF.getText());
        int accountcolumn = 0;
        int row = userTable.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Anda belum memilih tujuan transfer","TUJUAN TRANSFER",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(amount==0){
           JOptionPane.showMessageDialog(null, "Silahkan masukkkan jumlah tarik tunai yang valid (min Rp 1)","AMOUNT INVALID",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
        System.out.println(row);
        String to = (String)userTable.getValueAt(row, accountcolumn);
        
        boolean success = ATMController.getInstance().doTransfer(amount, to);
        if(success){
           JOptionPane.showMessageDialog(null, "Tranfer senilai " + amount+ " ke rekening " + to+" berhasil\nSilahkan cek saldo anda","STATUS TRANSFER",JOptionPane.INFORMATION_MESSAGE);
           
       }else{
            JOptionPane.showMessageDialog(null, "Gagal transfer\nPastikan saldo anda mencukupi","STATUS TRANSFER",JOptionPane.ERROR_MESSAGE);
            
        }
        
        
       
    }//GEN-LAST:event_trfConfirmBtnActionPerformed

    private void trfCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trfCancelBtnActionPerformed
        transferDialog.setVisible(false);
    }//GEN-LAST:event_trfCancelBtnActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        depositDialog.getContentPane().setBackground( new Color(0,153,255) );
        depositDialog.setSize(200, 100);
        depositDialog.pack();
        depositDialog.setLocation((dim.width - withdrawDialog.getWidth()) / 2, (dim.height - withdrawDialog.getHeight()) / 2);
        depositDialog.setResizable(false);
        depositDialog.setVisible(true);
    }//GEN-LAST:event_depositBtnActionPerformed

    private void withdrawalCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalCancelBtnActionPerformed
        withdrawDialog.setVisible(false);
    }//GEN-LAST:event_withdrawalCancelBtnActionPerformed

    private void depositConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositConfirmBtnActionPerformed
        Integer amount = Integer.parseInt(depositAmountTF.getText());
       boolean success = ATMController.getInstance().doDeposit(amount);
       if(amount==0){
           JOptionPane.showMessageDialog(null, "Silahkan masukkkan deposit yang valid (min Rp 1)","AMOUNT INVALID",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       if(success){
           JOptionPane.showMessageDialog(null, "Deposit Berhasil","STATUS DEPOSIT",JOptionPane.INFORMATION_MESSAGE);
       }else{
            JOptionPane.showMessageDialog(null, "Deposit Gagal","STATUS DEPOSIT",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_depositConfirmBtnActionPerformed

    private void depositCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositCancelBtnActionPerformed
         depositDialog.setVisible(false);
    }//GEN-LAST:event_depositCancelBtnActionPerformed

    private void depositBtnComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_depositBtnComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_depositBtnComponentHidden

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberTF;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JTextField depositAmountTF;
    private javax.swing.JButton depositBtn;
    private javax.swing.JButton depositCancelBtn;
    private javax.swing.JButton depositConfirmBtn;
    private javax.swing.JDialog depositDialog;
    private javax.swing.JLabel fullnameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelSelamatDatang;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JPanel panelWithdrawal;
    private javax.swing.JButton transferBtn;
    private javax.swing.JDialog transferDialog;
    private javax.swing.JTextField trfAmountTF;
    private javax.swing.JButton trfCancelBtn;
    private javax.swing.JButton trfConfirmBtn;
    private javax.swing.JTable userTable;
    private javax.swing.JSeparator welcomeSeparator;
    private javax.swing.JTextField withDrawAmountTF;
    private javax.swing.JDialog withdrawDialog;
    private javax.swing.JButton withdrawalBtn;
    private javax.swing.JButton withdrawalCancelBtn;
    private javax.swing.JButton withdrawalConfirmBtn;
    // End of variables declaration//GEN-END:variables

    
}
